services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo_container:27017/app-shopper
      - FRONTEND_URI=http://localhost
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ROUTES_API_URI=https://routes.googleapis.com/directions/v2:computeRoutes
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REACT_APP_BACKEND_URI=http://localhost:8080

volumes:
  mongo-data:
